[package]
name = "rshijack"
version = "0.1.0"
description = "rust rewrite of shijack"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/rshijack"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
clap = "2"
pcap = "0.7"
env_logger = "0.5"
log = "0.4"
error-chain = "0.11"
pktparse = "0.2"
nom = "3"
pnet = "0.20"
